export const RUNTIME_ENV = Symbol("RUNTIME_ENV");
export const FOUNDATION_REPOSITORY = Symbol("FOUNDATION_REPOSITORY");
export const MODERATION_REPOSITORY = Symbol("MODERATION_REPOSITORY");
export const ANTIFLOOD_REPOSITORY = Symbol("ANTIFLOOD_REPOSITORY");
export const CAPTCHA_REPOSITORY = Symbol("CAPTCHA_REPOSITORY");
export const CONTENT_LOCK_REPOSITORY = Symbol("CONTENT_LOCK_REPOSITORY");
export const ANTIRAID_REPOSITORY = Symbol("ANTIRAID_REPOSITORY");
export const NOTES_REPOSITORY = Symbol("NOTES_REPOSITORY");
export const FILTERS_REPOSITORY = Symbol("FILTERS_REPOSITORY");
export const WELCOME_REPOSITORY = Symbol("WELCOME_REPOSITORY");
export const REPUTATION_REPOSITORY = Symbol("REPUTATION_REPOSITORY");
export const INVITE_REPOSITORY = Symbol("INVITE_REPOSITORY");
export const ANALYTICS_REPOSITORY = Symbol("ANALYTICS_REPOSITORY");
export const POLL_REPOSITORY = Symbol("POLL_REPOSITORY");
export const GIVEAWAY_REPOSITORY = Symbol("GIVEAWAY_REPOSITORY");
export const SCHEDULED_POST_REPOSITORY = Symbol("SCHEDULED_POST_REPOSITORY");
export const TICKET_REPOSITORY = Symbol("TICKET_REPOSITORY");
export const PRODUCTIVITY_REPOSITORY = Symbol("PRODUCTIVITY_REPOSITORY");
export const FEED_REPOSITORY = Symbol("FEED_REPOSITORY");
export const FILE_REPOSITORY = Symbol("FILE_REPOSITORY");
export const GAME_REPOSITORY = Symbol("GAME_REPOSITORY");
export const CHIP_REPOSITORY = Symbol("CHIP_REPOSITORY");
export const AI_REPOSITORY = Symbol("AI_REPOSITORY");
export const AI_PROVIDER = Symbol("AI_PROVIDER");
export const PAYMENT_REPOSITORY = Symbol("PAYMENT_REPOSITORY");
export const PLATFORM_REPOSITORY = Symbol("PLATFORM_REPOSITORY");
export const MODERATION_EXTRA_REPOSITORY = Symbol(
  "MODERATION_EXTRA_REPOSITORY",
);
export const WEBHOOK_REPOSITORY = Symbol("WEBHOOK_REPOSITORY");
export const CUSTOM_COMMAND_REPOSITORY = Symbol("CUSTOM_COMMAND_REPOSITORY");
export const D1_REPOSITORY = Symbol("D1_REPOSITORY");
export const OWNER_NETWORK_REPOSITORY = Symbol("OWNER_NETWORK_REPOSITORY");
export const GROUP_PROTECTION_REPOSITORY = Symbol(
  "GROUP_PROTECTION_REPOSITORY",
);
export const QUOTE_RENDERER = Symbol("QUOTE_RENDERER");
export const SPAM_CHECK_PROVIDER = Symbol("SPAM_CHECK_PROVIDER");
export const FEDERATION_REPOSITORY = Symbol("FEDERATION_REPOSITORY");
export const FEEDBACK_REPOSITORY = Symbol("FEEDBACK_REPOSITORY");
export const STAFF_NOTE_REPOSITORY = Symbol("STAFF_NOTE_REPOSITORY");
export const ECONOMY_REPOSITORY = Symbol("ECONOMY_REPOSITORY");
export const INCIDENT_REPOSITORY = Symbol("INCIDENT_REPOSITORY");
export const COOP_MISSION_REPOSITORY = Symbol("COOP_MISSION_REPOSITORY");
export const GRATITUDE_REPOSITORY = Symbol("GRATITUDE_REPOSITORY");
export const FLOOD_COUNTER = Symbol("FLOOD_COUNTER");
export const TELEGRAM_GATEWAY = Symbol("TELEGRAM_GATEWAY");
export const OWNER_NETWORK_RISK_REPOSITORY = Symbol(
  "OWNER_NETWORK_RISK_REPOSITORY",
);
export const GAMIFICATION_REPOSITORY = Symbol("GAMIFICATION_REPOSITORY");
export const AUTOMATION_REPOSITORY = Symbol("AUTOMATION_REPOSITORY");
export const AI_ACCESS_REPOSITORY = Symbol("AI_ACCESS_REPOSITORY");
export const CHAT_ACTIVITY_REPOSITORY = Symbol("CHAT_ACTIVITY_REPOSITORY");
export const CHAT_SETTING_REPOSITORY = Symbol("CHAT_SETTING_REPOSITORY");
export const GUARDIAN_REPOSITORY = Symbol("GUARDIAN_REPOSITORY");
// NEW: playlist-battle / creativity-challenge wiring (battle-entries-repository).
export const BATTLE_ENTRIES_REPOSITORY = Symbol("BATTLE_ENTRIES_REPOSITORY");
