// Pure resolver + paytable for Telegram's native 🎯 dart emoji (sendDice "🎯").
// Telegram returns dice.value in 1..6 which we treat as ~UNIFORM 1..6 (the true
// distribution is close enough to uniform for pricing; unlike the 🎰 slot the
// dart is effectively a fair d6). The outcome is generated by Telegram — we only
// classify + price it here, so the bot cannot rig the throw.
//
// The player bets on which RING the dart will land in:
//   value 1-3 -> "fuera"  (outer, 3 of 6 ways)
//   value 4-5 -> "aro"    (ring,  2 of 6 ways)
//   value 6   -> "diana"  (bullseye, 1 of 6 ways)
// A bet wins only when the dart's landed tier equals the chosen tier.

export type DartTier = "fuera" | "aro" | "diana";

/** Config-free house edge for the dart game. */
export const BULLSEYE_HOUSE_EDGE = 0.05;

/** Number of d6 faces that resolve to each tier (the win "ways" out of 6). */
export const BULLSEYE_WAYS: Readonly<Record<DartTier, number>> = {
  fuera: 3,
  aro: 2,
  diana: 1,
};

export interface BullseyeDetail {
  readonly value: number;
  readonly tier: DartTier;
  readonly landed: DartTier;
  readonly win: boolean;
}

const round2 = (n: number): number => Math.round(n * 100) / 100;

/** True for a valid native dart value (integer 1..6). */
export const isBullseyeValue = (value: number): boolean =>
  Number.isInteger(value) && value >= 1 && value <= 6;

/** Classify a raw dart value 1..6 into the ring it landed in. */
export const landedTier = (value: number): DartTier => {
  if (value >= 6) {
    return "diana";
  }
  if (value >= 4) {
    return "aro";
  }
  return "fuera";
};

/**
 * Fair payout multiplier (× stake) for betting a given tier, on a win only.
 * multiplier = round2((6 / ways) × (1 − edge)); a loss is always 0.
 * With ways/6 win chance this yields a flat 5% house edge across all tiers:
 *   fuera 1.9 · aro 2.85 · diana 5.7.
 */
export const bullseyeMultiplier = (
  tier: DartTier,
  edge: number = BULLSEYE_HOUSE_EDGE,
): number => {
  const ways = BULLSEYE_WAYS[tier];
  return round2((6 / ways) * (1 - edge));
};

/**
 * Resolve a dart throw: the player bet on `tier`, Telegram returned `value`.
 * Returns the payout multiplier (0 on loss) and a detail object for display.
 */
export const resolveBullseye = (
  value: number,
  tier: DartTier,
  edge: number = BULLSEYE_HOUSE_EDGE,
): { multiplier: number; detail: BullseyeDetail } => {
  const landed = landedTier(value);
  const win = landed === tier;
  return {
    multiplier: win ? bullseyeMultiplier(tier, edge) : 0,
    detail: { value, tier, landed, win },
  };
};

const TIER_LABEL: Readonly<Record<DartTier, string>> = {
  fuera: "Fuera",
  aro: "Aro",
  diana: "Diana",
};

/** One-line Spanish render of a resolved dart throw. */
export const describeBullseye = (detail: BullseyeDetail): string => {
  const mult = bullseyeMultiplier(detail.tier);
  const apuesta = TIER_LABEL[detail.tier];
  const cayo = TIER_LABEL[detail.landed];
  if (detail.win) {
    return `🎯 ¡Diana! Apostaste ${apuesta} y cayó en ${cayo} (dardo ${detail.value}) — ganas ×${mult}`;
  }
  return `🎯 Fallo. Apostaste ${apuesta} pero cayó en ${cayo} (dardo ${detail.value}) — pierdes`;
};
