// Pure decoder + paytable for Telegram's native 🎰 slot machine (sendDice emoji
// "🎰"). Telegram returns dice.value in 1..64 which fully encodes the three reels,
// so the outcome is generated by Telegram (provably fair by construction — the bot
// cannot rig it) and we only DECODE + price it here.
//
// Encoding: v = value - 1 (0..63); each reel is a base-4 digit of v:
//   left = v & 3, middle = (v >> 2) & 3, right = (v >> 4) & 3
// Symbol index 0..3 = [BAR, GRAPE, LEMON, SEVEN]. The four triples are therefore
// value 1 (BAR·BAR·BAR), 22 (GRAPE³), 43 (LEMON³) and 64 (SEVEN³ = the jackpot).

export const SLOT_SYMBOLS = ["bar", "grape", "lemon", "seven"] as const;
export type SlotSymbol = (typeof SLOT_SYMBOLS)[number];

export interface SlotSpin {
  readonly value: number;
  readonly reels: readonly [SlotSymbol, SlotSymbol, SlotSymbol];
  readonly kind: "triple" | "pair" | "none";
  /** The matched symbol for a triple/pair, else null. */
  readonly symbol: SlotSymbol | null;
}

export const isSlotValue = (value: number): boolean =>
  Number.isInteger(value) && value >= 1 && value <= 64;

const symbolAt = (index: number): SlotSymbol =>
  SLOT_SYMBOLS[index] as SlotSymbol;

export const decodeSlot = (value: number): SlotSpin => {
  const v = value - 1;
  const reels: [SlotSymbol, SlotSymbol, SlotSymbol] = [
    symbolAt(v & 3),
    symbolAt((v >> 2) & 3),
    symbolAt((v >> 4) & 3),
  ];
  const [a, b, c] = reels;
  if (a === b && b === c) {
    return { value, reels, kind: "triple", symbol: a };
  }
  // A "pair" = the two leftmost reels match (the visual left-to-right read).
  if (a === b) {
    return { value, reels, kind: "pair", symbol: a };
  }
  return { value, reels, kind: "none", symbol: null };
};

/**
 * Payout multiplier table (× stake). Triples pay big — the SEVEN triple (value 64)
 * is the jackpot. A leftmost pair returns a small consolation. These are DEFAULTS:
 * Telegram's 1..64 distribution is NOT uniform, so calibrate the exact multipliers
 * against measured value frequencies before going live (see fairness/economy notes).
 */
export interface SlotPaytable {
  readonly triple: Readonly<Record<SlotSymbol, number>>;
  readonly pair: number;
}

export const DEFAULT_SLOT_PAYTABLE: SlotPaytable = {
  triple: { seven: 20, bar: 12, grape: 8, lemon: 8 },
  pair: 1.5,
};

/** Multiplier applied to the stake for a decoded spin (0 = loss). */
export const slotMultiplier = (
  spin: SlotSpin,
  paytable: SlotPaytable = DEFAULT_SLOT_PAYTABLE,
): number => {
  if (spin.kind === "triple" && spin.symbol) {
    return paytable.triple[spin.symbol];
  }
  if (spin.kind === "pair") {
    return paytable.pair;
  }
  return 0;
};

/** True for the top jackpot line (triple sevens = Telegram value 64). */
export const isJackpot = (spin: SlotSpin): boolean =>
  spin.kind === "triple" && spin.symbol === "seven";
