// SlotStorm — in-chat Telegram casino game for the native slot machine (🎰).
//
// Telegram's sendDice with emoji "🎰" returns dice.value in 1..64, which fully
// encodes the three reels. The outcome is therefore generated by Telegram itself
// (provably fair by construction) and this module only DECODES + PRICES it —
// it never generates randomness. Pure & deterministic: no I/O, DB, Date.now,
// Math.random or network.
//
// The 1..64 distribution is NON-uniform (Telegram under-weights triples/pairs),
// so we deliberately reuse slot.ts's conservative DEFAULT_SLOT_PAYTABLE as the
// single source of truth for the economy and do NOT re-tune multipliers here.

import {
  decodeSlot,
  isJackpot,
  type SlotSymbol,
  slotMultiplier,
} from "./slot.js";

/** Display payload for one resolved SlotStorm spin. */
export interface SlotGameDetail {
  readonly reels: readonly [SlotSymbol, SlotSymbol, SlotSymbol];
  readonly jackpot: boolean;
  readonly multiplier: number;
}

/** Emoji shown for each reel symbol in the Spanish UI. */
export const SLOT_EMOJI: Readonly<Record<SlotSymbol, string>> = {
  bar: "🍫",
  grape: "🍇",
  lemon: "🍋",
  seven: "7️⃣",
};

/**
 * Resolve a Telegram 🎰 dice value (1..64) into a payout multiplier (× stake,
 * 0 = loss) plus a display detail. Decoding + pricing are delegated to the
 * shared slot.js primitives so the paytable stays a single source of truth.
 */
export const resolveSlot = (
  value: number,
): { multiplier: number; detail: SlotGameDetail } => {
  const spin = decodeSlot(value);
  const multiplier = slotMultiplier(spin);
  const detail: SlotGameDetail = {
    reels: spin.reels,
    jackpot: isJackpot(spin),
    multiplier,
  };
  return { multiplier, detail };
};

/** Emoji for a single reel symbol (guarded for noUncheckedIndexedAccess). */
const emojiFor = (symbol: SlotSymbol): string => SLOT_EMOJI[symbol] ?? "❓";

/**
 * One-line Spanish render of a resolved spin, e.g.
 *   "7️⃣ 7️⃣ 7️⃣ — ¡JACKPOT! x20"
 *   "🍫 🍫 🍫 — ¡Triple! x12"
 *   "🍇 🍇 🍋 — Sin premio x0"
 */
export const describeSlot = (detail: SlotGameDetail): string => {
  const [a, b, c] = detail.reels;
  const line = `${emojiFor(a)} ${emojiFor(b)} ${emojiFor(c)}`;
  const mult = `x${detail.multiplier}`;
  if (detail.jackpot) {
    return `${line} — ¡JACKPOT! ${mult}`;
  }
  if (detail.multiplier === 0) {
    return `${line} — Sin premio ${mult}`;
  }
  const win = a === b && b === c ? "¡Triple!" : "¡Par!";
  return `${line} — ${win} ${mult}`;
};
